# This simulates the below client:

# kubectl run client -n mesh-exp --image=curlimages/curl -it --rm -- sh
# apk add wrk <- I replaced it by fortio (a better load testing tool native to istio better than even wrk2)

apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: mesh-exp
  labels:
    app: client
spec:
  nodeSelector:
    exp: mesh

  containers:
  - name: client
    image: fortio/fortio:latest

    # Run Fortio server mode (keeps container alive)
    args: ["server"]

    # Mount writable directory for JSON outputs
    volumeMounts:
    - name: data
      mountPath: /data

    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "500m"

  # Writable volume (FIXES /data issue)
  volumes:
  - name: data
    emptyDir: {}