apiVersion: v1
kind: Pod
metadata:
  name: wrk-client
  namespace: exp-2-istio
  labels:
    app: wrk-client
spec:
  nodeSelector:
    kubernetes.io/hostname: ssp-worker-2
  containers:
  - name: wrk
    image: williamyeh/wrk
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"