# Services for the 2 deployments svc-a-deployment and svc-b-deployment.
# Both exposed on port 80 for uniform access from client.

apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: mesh-exp
spec:
  selector:
    app: svc-a
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: mesh-exp
spec:
  selector:
    app: svc-b
  ports:
  - port: 80
    targetPort: 5678
