apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: exp-1-baseline
  labels:
    app: http-server
spec:
  nodeSelector:
    kubernetes.io/hostname: ssp-worker-1
  containers:
  - name: server
    image: hashicorp/http-echo
    args:
      - "-text=hello"
    ports:
      - containerPort: 5678
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"