apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  namespace: exp-1-baseline
  labels:
    app: iperf-server
spec:
  nodeSelector:
    kubernetes.io/hostname: ssp-worker-1
  containers:
  - name: iperf
    image: networkstatic/iperf3
    command: ["iperf3", "-s"]